name: "ggt deploy"
description: "Run a deploy from ggt"
inputs:
  app:
    description: "Which app to deploy to"
    required: true
  environment:
    description: "Which environment to push to and then deploy from"
    required: true
  token:
    description: "The ggt token to use for authentication"
    required: true
  allow-issues:
    description: "Whether to ignore issues and deploy anyway"
    required: false
    default: 'false'
  allow-data-delete:
    description: "Whether to allow data deletion"
    required: false
    default: 'false'
  allow-charges:
    description: "Whether to allow incurring charges as part of the deploy"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Install ggt
      run: |
        npm install -g ggt@latest
        ggt version
      shell: bash

    - name: Deploy to production
      run: |
        ggt deploy --app=${{ inputs.app }} --from=${{ inputs.environment }} --force --allow-unknown-directory ${{ inputs.allow-issues == 'true' && '--allow-issues' || '' }} ${{ inputs.allow-data-delete == 'true' && '--allow-data-delete' || '' }} ${{ inputs.allow-charges == 'true' && '--allow-charges' || '' }}
      shell: bash
      env:
        GGT_TOKEN: ${{ inputs.token }}
